window:
  padding:
    x: 10
    y: 10

  dynamic_padding: true
  dynamic_title: false

font:
  normal:
    family: Iosevka
    style: Medium Extended

  size: 10.0
  scale_with_dpi: false

draw_bold_text_with_bright_colors: false

colors:
  primary:
    background: '#3f3f3f'

live_config_reload: true
