{ config, options, pkgs, lib, ... }:

with lib;
{
  options.modules.dev.agda = {
    enable = mkOption {
      type = types.bool;
      default = false;
    };
  };

  config = mkIf config.modules.dev.agda.enable {
    home.packages = with pkgs; [
      (agda.withPackages {
        pkgs = [ ];
      })
      (agda-pkg.overrideAttrs (old: {
        installPhase =
          ''
              pipInstallPhase

            cat >"$out/lib/python3.10/site-packages/apkg/commands/templates/gitignore.template" <<'END'
            ### Agda ###
            *.agdai
            *.hi
            *.o
            *.agda#
            *.agda~
            .#*.agda
            ./agda-stdlib
            END

            cat >"$out/lib/python3.10/site-packages/apkg/commands/templates/library.agda-lib" <<'END'
            -- File generated by Agda-Pkg
            name:    {{name}}
            {% if depend|length > 0 -%}
            depend:  {{depend|join(' ')}}
            {%- endif %}
            {% if include|length > 0 -%}
            include: {{include|join(' ')}}
            {%- endif %}
            -- End {{"\n"}}
            END

            cat >"$out/lib/python3.10/site-packages/apkg/commands/templates/library.agda-pkg" <<'END'
            # File generated by Agda-Pkg
            name:              {{name}}
            version:           {{version}}
            {% if authors|length > 0 -%}
            author:            {% if authors|length == 1 -%}{{authors[0]}}  
              {%- else -%}
              {%- for author in authors %}
                - {{author}}
              {%- endfor %}  
              {%- endif %}
            {%- endif %}
            {% if categories|length > 0 -%}
            category:          {{categories|join(', ')}}
            {%- endif %}
            {% if homepage|length > 0 -%}
            homepage:          {{homepage}}
            {%- endif %}
            {% if license|length > 0 -%}
            license:           {{license}}
            license-file:      LICENSE.md
            {%- endif %}
            {% if sourceRepository|length > 0 -%}
            source-repository: {{sourceRepository}}
            {%- endif %}
            {% if testedWith|length > 0 -%}
            tested-with:       {{testedWith|join(', ')}}
            {%- endif %}
            {% if description|length > 0 -%}
            description:       {{description}}
            {%- endif %}
            {% if depend|length > 0 -%}
            depend:
              {%- for lib in depend %}
                - {{lib}}
              {%- endfor %}
            {% endif %}
            {%- if include|length > 0 -%}
            include:
              {%- for path in include %}
                - {{path}}
              {%- endfor %}
            {%- endif %}
            # End {{"\n"}}
            END
          '';
        # This sucks as a hack but it is necessary because the PyPi release does not contain those files
      }))
    ];
  };
}

