[server]
timeout = 3600 # 60 minutes

[language.haskell]
filetypes = ["haskell"]
roots = ["Setup.hs", "stack.yaml", "*.cabal"]
command = "haskell-language-server-wrapper"
args = ["--lsp"]

[language.latex]
filetypes = ["latex"]
roots = ["main.tex"]
command = "texlab"
args = []

[language.rust]
filetypes = ["rust"]
roots = ["Cargo.toml"]
command = "rls"
