[server]
timeout = 3600 # 60 minutes

[language.haskell]
filetypes = ["haskell"]
roots = ["Setup.hs", "stack.yaml", "*.cabal"]
command = "haskell-language-server-wrapper"
args = ["--lsp"]

[language.latex]
filetypes = ["latex"]
roots = ["main.tex"]
command = "texlab"
args = []

[language.rust]
filetypes = ["rust"]
roots = ["Cargo.toml"]
command = "rls"

[language.c_cpp]
filetypes = ["c", "cpp"]
roots = ["compile_commands.json", ".ccls", ".git"]
command = "ccls"
# Disable additional information in autocompletion menus that Kakoune inserts into the buffer until https://github.com/ul/kak-lsp/issues/40 gets fixed
args = ["--init={\"completion\":{\"detailedLabel\":false}}"]

[language.nix]
filetypes = ["nix"]
roots = ["shell.nix", "default.nix", "home.nix", ".git"]
command = "rnix-lsp"

[language.python]
filetypes = ["python"]
roots = []
command = "pylsp"
